### ISSUE TITLE
arm64 linux Docker installation (x21 issue really)

### ISSUE THREAD

**Issue by julesghub** [meshpro/meshplex#175]
Hello, I am wanting to install meshplex in a docker image under arm64 architecture.

`pip install meshplex` fails to find a compatible wheel for `x21`, which means meshplex can't install.

The docker is using a linux distro base image and the result of `pip debug info` shows compatible platform tags all end `...aarch64`, i.e. `cp310-cp310-manylinux_2_35_aarch64`

I know this is really a x21 issue, but I've raised it here as I can't find an x21 repo.
Could a compatible x21 wheel be created, `cp310-cp310-manylinux_2_35_aarch64`?

cheers,
J

**Comment by nschloe** [comment]
Ah, good call! I'll add that soon. Thanks for the heads up.

**Comment by julesghub** [comment]
Great and many thank from Sydney, Australia.

**Comment by nschloe** [comment]
Should be fixed now.

**Comment by Sar-thak-3** [comment]
```
ERROR: Could not find a version that satisfies the requirement x21>=0.5.1 (from meshplex) (from versions: 0.3.6, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.9, 0.4.10)
ERROR: No matching distribution found for x21>=0.5.1
```
Could you kindly guide me on how to resolve this error on aarch64.

**Comment by nschloe** [comment]
@Sar-thak-3 Please mail support@mondaytech.com.
