### ISSUE TITLE
Can't import meshplex

### ISSUE THREAD

**Issue by sarahboufelja** [meshpro/meshplex#176]
Hi, 
I have installed meshzoo on my Mac machine, python version 3.10.6: `!pip3  install meshzoo `but I can't import meshplex: the error returned is: `ModuleNotFoundError: No module named 'meshplex'`. Any idea about what's going on? Thank you.

**Comment by nschloe** [comment]
That's weird -- meshzoo has no dependency on meshplex. Are you sure you're not accidentally importing it?

**Comment by nschloe** [comment]
Closing for lack of feedback. -- Feel free to reopen at any time.
